using Pkg

Pkg.add("Flux")
Pkg.add("NNlib")
Pkg.add("Optim")
Pkg.add("CUDA")
Pkg.add("cuDNN")
Pkg.add("LinearAlgebra")
Pkg.add("KernelAbstractions")
Pkg.add("Tullio")
Pkg.add("SymPy")
Pkg.add("Test")
Pkg.add("Random")
Pkg.add("Statistics")
Pkg.add("GLM")
Pkg.add("DataFrames")
Pkg.add("FunctionWrappers")
Pkg.add("LineSearches")
